version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'yarn install' # run a custom app build step
      - cypress/run:
          command: ls
          command: cd e2e
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboard
          start: 'yarn start' # start server before running tests
