version: 2.1
orbs:
  slack: circleci/slack@4.2.0
  cypress: cypress-io/cypress@1
executors:
  node:
    docker:
      - image: circleci/node:14.15.0
    working_directory: /tmp
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
  save_modules:
    steps:
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run: mkdir -p workspace
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: workspace 
          paths:
            - echo-output
#      - slack/notify:
#          channel: C01J25XKYDS
#          event: fail
#          template: basic_fail_1
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: unit test
          command: yarn test
      - slack/notify:
          channel: C01J25XKYDS
          event: fail
          template: basic_fail_1
  deploy:
    executor:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: deploy S3
          command: aws s3 sync ./echo-output/ s3://ene-contents --delete

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - cypress/run:
          yarn: true
          post-steps:
            - store_artifacts:
                path: e2e/videos
          command: 'yarn cy:run'
          start: 'yarn start' # start server before running tests
          wait-on: 'http://localhost:3000'
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
